# Generated by Django 3.1.5 on 2021-09-30 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20210930_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverycontainer',
            name='order',
        ),
    ]
