# Generated by Django 3.1.5 on 2021-10-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_remove_deliverycontainer_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverycontainer',
            name='order_in_container',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
