# Generated by Django 3.1.5 on 2021-11-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_deliverycontainer_order_in_container'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverycontainer',
            name='fa_date',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
