# Generated by Django 3.1.5 on 2021-11-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_deliverycontainer_fa_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverycontainer',
            name='fa_time',
            field=models.CharField(choices=[('9-12', '9-12'), ('13-16', '13-16')], default='morning', max_length=200),
        ),
    ]
