# Generated by Django 3.1.5 on 2021-11-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_auto_20211103_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverycontainer',
            name='fa_time',
            field=models.CharField(choices=[('9:00-12:00', '9-12'), ('13:00-16:00', '13-16')], default='morning', max_length=200),
        ),
    ]
