# Generated by Django 3.1.5 on 2021-11-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='fav_address',
            field=models.BooleanField(default=False, verbose_name='Favorite address'),
        ),
    ]
