# Generated by Django 3.1.5 on 2021-09-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_page_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='image_alt',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
