# Generated by Django 3.1.5 on 2021-09-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_page_image_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image_alt',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
