# Generated by Django 3.1.5 on 2021-06-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='sliders/')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
