# Generated by Django 3.1.5 on 2021-07-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='temp_product',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
