# Generated by Django 3.1.5 on 2021-07-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210714_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_measure',
            field=models.CharField(blank=True, choices=[('gram', 'گرم'), ('kilogram', 'کیلوگرم'), ('litre', 'لیتر')], max_length=50, null=True),
        ),
    ]
