# Generated by Django 3.1.5 on 2021-07-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210722_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
