# Generated by Django 3.1.5 on 2021-10-01 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20210806_0829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='temp_product',
        ),
    ]
