# Generated by Django 3.1.5 on 2021-09-02 16:42

from django.db import migrations
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210902_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fa_date',
            field=django_jalali.db.models.jDateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
