# Generated by Django 3.1.5 on 2021-09-14 05:27

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_fa_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fa_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
