# Generated by Django 3.1.5 on 2021-09-30 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_remove_deliverycontainer_order'),
        ('orders', '0008_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.deliverycontainer'),
        ),
    ]
