# Generated by Django 3.1.5 on 2021-09-30 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_delivery_container'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivered',
        ),
    ]
