# Generated by Django 3.1.5 on 2021-11-02 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_deliverycontainer_order_in_container'),
        ('orders', '0012_order_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.deliverycontainer', verbose_name='Delivery container'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Phone'),
        ),
    ]
